### ISSUE TITLE
Add license?

### ISSUE THREAD

**Issue by mrcjkb** [nvim-lua/nvim-lua-plugin-template#12]
I just noticed that this template does not have a license.

According to the [GitHub docs](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license):

> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. 

If the license was left out deliberately, so that people can choose their own, I would suggest adding a permissive license like [WTFPL](http://www.wtfpl.net/).

**Comment by mfussenegger** [comment]
I added some text about the license to the readme: https://github.com/nvim-lua/nvim-lua-plugin-template/commit/b72806c62bd5ec686e05678479700ef09022709c 

No idea if that's legally sufficient, but I don't want to add the license file as it shouldn't be included in the repos that get created from this template.

**Comment by mrcjkb** [comment]
That should be legally sufficient. Thanks :smile:
