### ISSUE TITLE
Code examples for best practice

### ISSUE THREAD

**Issue by matu3ba** [nvim-lua/nvim-lua-plugin-template#3]
Always check existence of dependencies (except for transitive dependencies) of upstream project you depend on:
```lua
local has_telescope, telescope = pcall(require, 'telescope')
if not has_telescope then
  error('This plugins requires nvim-telescope/telescope.nvim')
end
```

If possible, provide a setup function for the user in your `$GIT_ROOT/lua/yourpluginname.lua`:
```lua
-- your imports
...
local M = {}
function M.setup()
-- plugin setup code
...
end
...
return M
```
```lua
-- The user can then use it (for example with packer)
use { 'yourname/yourpluginname.nvim', config = function() require('yourpluginname').setup() end }
-- or alternatively somewhere in the lua or vim config
require('yourpluginname').setup()
```
Using `M` for all members of a file (variables and functions) is best practice.

**Comment by mfussenegger** [comment]
See https://github.com/nvim-lua/nvim-lua-plugin-template/issues/2#issuecomment-900452800
