### ISSUE TITLE
Performance tips

### ISSUE THREAD

**Issue by matu3ba** [nvim-lua/nvim-lua-plugin-template#4]
1. Make sure the problem is not too complex for lua 5.1 and the lua ecosystem, so your effort will have results. 
2. Prototype a minimal viable product to understand performance tradeoffs on the problem.

Sources to decide 1: 
luajit wiki http://wiki.luajit.org/Home
luajit not implemented http://wiki.luajit.org/NYI#libraries_string-library
numerical computing guide http://wiki.luajit.org/Numerical-Computing-Performance-Guide
scilua https://scilua.org/optimizing.html

plenary.nvim
nvim wishlist (what is missing in lua for neovim)

Other typical used languages to use (for a subpart of your problem):
- fennel
- python
- nodejs/typescript
- C
- Rust
- ...

We want to keep it short except for lua, since there are no good documents elsewhere.

**Comment by mfussenegger** [comment]
See https://github.com/nvim-lua/nvim-lua-plugin-template/issues/2#issuecomment-900452800
