### ISSUE TITLE
Problem: Enforce and check if lua functions of plugins are local (and global ones documented)

### ISSUE THREAD

**Issue by matu3ba** [nvim-lua/nvim-lua-plugin-template#5]
This also is a workaround of not forcing plugin authors to provide commands for faster configuration of plugins:
https://www.reddit.com/r/neovim/comments/p56fwb/psa_plugin_authors_create_vim_commands_for_your/

The idea is to 
1. get the list of loaded files
2. use treesitter queries/lua tables to get local functions with scope of file/global functions
3. provide the local/global function list per file

Preview inside treesitter/fzf or another options and dumb it inside a buffer for copying by the user.

Are there solutions to this use case already?

**Comment by mfussenegger** [comment]
See https://github.com/nvim-lua/nvim-lua-plugin-template/issues/2#issuecomment-900452800
